selected_system_id: 'Brandenburg_Fernwaerme.1'  # The ID of the district heating system you want to analyze
max_distance: 1000                              # The maximum distance for proximity analysis in meters