
results_dir: 'results'


###################
# Scenario controls

run: '1run_5_Szenario_all_res_tech_redispatch'
# 1run_5_Szenario_all_tech (dies ist ohne gas)

# wildcards
scenario:
  selected_system_id: #[
    'Brandenburg_Fernwaerme.29' #, 'Brandenburg_Fernwaerme.2'
  #]
  year_of_interest: #[
    '2018' #, '2020'
  #]
  supply_temp: #[
    90 #,70, 110
  #]
  return_temp: #[
    50 #,50
  #]
  costs_data_year: #[
    '2025' #,'2030' ,'2035'
  #]
  r: #[
    7 #,5 ,8
  #]
  electricity_price: #[
    130 #,100 ,400
  #]
  co2_price: #[
    80 #,60 ,70
  #]
  gas_price: #[
    50 #,60 ,70
  #]



components_enabled:
  central excess-heat heat pump: true
  central sourced-water heat pump: true
  central sourced-sea heat pump: true
  central air sourced heat pump: true
  central H2 boiler: true
  central electric boiler: true
  central gas boiler: false
  electrolysis AEC: true
  electrolysis PEMEC: true
  central water tank storage: true
  PTES: true
  battery: true
  H2 store: true
  redispatch wind power: true

###################
# fixed settings

cost_functions: # also applies for linearizing_costs!!!!
  inflation_2024: 0.0353  # 3.53%
  inflation_2025: 0.022  # 2.2%
  project_year: '2025'
  Abwaerme: 50 # temperature of electrolysis excess heat
  min_temp_thresholds:
      Luft: -5
      Flussthermie: 3
      Seethermie: 3
      Abwaerme: 0
  cp: 1.1625
  rho: 1000


data_energieportal:
  max_distance: 1000   # The maximum distance for proximity analysis in meters

heat_demand:
  base_temperature: 15  # Base temperature for HDD calculation
  hot_water_demand_percentage: 25  # Percentage of total heat demand attributed to hot water
  heating_season_start: 10  # September
  heating_season_end: 4  # April

financial_params:
  fill_values: 0.0
  r: 0.07
  nyears: 1
  year: 2025


component_parameters:
  "central electric boiler":
    lower_limit: 20
    upper_limit: 50000
    error_threshold: 20
  "electrolysis AEC":
    lower_limit: 200
    upper_limit: 100000
    error_threshold: 20
  "electrolysis PEMEC":
    lower_limit: 200
    upper_limit: 100000
    error_threshold: 20
  "central gas boiler":
    lower_limit: 10
    upper_limit: 50000
    error_threshold: 10
  "central H2 boiler":
    lower_limit: 10
    upper_limit: 50000
    error_threshold: 10
  "central excess-heat heat pump":
    lower_limit: 10
    upper_limit: 50000
    error_threshold: 20
  "central sourced-water heat pump":
    lower_limit: 10
    upper_limit: 50000
    error_threshold: 20
  "central air sourced heat pump":
    lower_limit: 10
    upper_limit: 50000
    error_threshold: 20
  "central sourced-sea heat pump":
    lower_limit: 50
    upper_limit: 50000
    error_threshold: 20
  "PTES":
    lower_limit: 5000
    upper_limit: 200000
    error_threshold: 70
  "central water tank storage":
    lower_limit: 50
    upper_limit: 50000
    error_threshold: 700
